
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Thu Apr 03 22:01:55 CDT 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int DIVIDE = 16;
  static final int SHORT = 51;
  static final int CHAR = 50;
  static final int CONST = 43;
  static final int GE = 23;
  static final int DOUBLE = 55;
  static final int CONTINUE = 35;
  static final int LPAREN = 6;
  static final int INT = 52;
  static final int REGISTER = 48;
  static final int FOR = 33;
  static final int MINUS = 14;
  static final int ELIPSES = 27;
  static final int STATIC = 46;
  static final int RPAREN = 7;
  static final int SEMICOLON = 4;
  static final int AND = 24;
  static final int LT = 20;
  static final int FUN = 38;
  static final int OR = 25;
  static final int COMMA = 5;
  static final int EXTERN = 45;
  static final int TYPEDEF = 39;
  static final int PLUS = 13;
  static final int ASSIGN = 26;
  static final int IF = 29;
  static final int DOT = 12;
  static final int ID = 2;
  static final int LE = 21;
  static final int EOF = 0;
  static final int RETURN = 36;
  static final int error = 1;
  static final int AUTO = 47;
  static final int NEQ = 19;
  static final int BREAK = 34;
  static final int VOID = 49;
  static final int EQ = 18;
  static final int LBRACK = 10;
  static final int TIMES = 15;
  static final int UNION = 41;
  static final int LBRACE = 8;
  static final int ELSE = 30;
  static final int ENUM = 42;
  static final int RBRACK = 11;
  static final int TO = 28;
  static final int WHILE = 31;
  static final int FLOAT = 54;
  static final int RBRACE = 9;
  static final int MODULUS = 17;
  static final int DECIMAL_LITERAL = 3;
  static final int LONG = 53;
  static final int VOLATILE = 44;
  static final int STRUCT = 40;
  static final int GT = 22;
  static final int VAR = 37;
  static final int DO = 32;

  /* non terminals */
  static final int simple_variable = 28;
  static final int let_expression = 23;
  static final int bitfield_list = 5;
  static final int struct_declaration_list = 7;
  static final int declaration_list = 1;
  static final int pointer_list = 10;
  static final int field_list = 18;
  static final int enumerator = 40;
  static final int $START = 0;
  static final int record_expression = 26;
  static final int compound_statement = 27;
  static final int initializer_list = 6;
  static final int variable_expression = 32;
  static final int initialization = 15;
  static final int struct_or_union = 38;
  static final int for_statement = 20;
  static final int name = 36;
  static final int integer_literal = 22;
  static final int if_statement = 21;
  static final int expression_array_type_list = 9;
  static final int operator_expression = 25;
  static final int bitfield_value = 37;
  static final int enumerator_list = 13;
  static final int expression = 14;
  static final int parameter_type_list = 12;
  static final int type_parameters = 4;
  static final int empty_array_type_list = 8;
  static final int brackets_list = 11;
  static final int type_name = 35;
  static final int empty_array_type = 39;
  static final int parameter_list = 3;
  static final int array_subscript = 30;
  static final int variable = 31;
  static final int while_statement = 33;
  static final int field_var = 19;
  static final int string_literal = 29;
  static final int function_call = 34;
  static final int parameters = 17;
  static final int expression_list = 16;
  static final int declaration = 2;
  static final int nil_expression = 24;
}

