
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Thu Apr 03 21:28:17 CDT 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int DIVIDE = 15;
  static final int SHORT = 49;
  static final int CHAR = 48;
  static final int CONST = 41;
  static final int GE = 22;
  static final int DOUBLE = 53;
  static final int LPAREN = 6;
  static final int CONTINUE = 33;
  static final int INT = 50;
  static final int REGISTER = 46;
  static final int FOR = 31;
  static final int MINUS = 13;
  static final int ELIPSES = 26;
  static final int STATIC = 44;
  static final int RPAREN = 7;
  static final int SEMICOLON = 4;
  static final int AND = 23;
  static final int LT = 19;
  static final int FUN = 36;
  static final int OR = 24;
  static final int COMMA = 5;
  static final int EXTERN = 43;
  static final int TYPEDEF = 37;
  static final int PLUS = 12;
  static final int ASSIGN = 25;
  static final int IF = 27;
  static final int ID = 2;
  static final int LE = 20;
  static final int EOF = 0;
  static final int RETURN = 34;
  static final int error = 1;
  static final int AUTO = 45;
  static final int NEQ = 18;
  static final int BREAK = 32;
  static final int VOID = 47;
  static final int EQ = 17;
  static final int LBRACK = 10;
  static final int TIMES = 14;
  static final int UNION = 39;
  static final int LBRACE = 8;
  static final int ELSE = 28;
  static final int ENUM = 40;
  static final int RBRACK = 11;
  static final int WHILE = 29;
  static final int FLOAT = 52;
  static final int RBRACE = 9;
  static final int MODULUS = 16;
  static final int DECIMAL_LITERAL = 3;
  static final int LONG = 51;
  static final int VOLATILE = 42;
  static final int STRUCT = 38;
  static final int GT = 21;
  static final int VAR = 35;
  static final int DO = 30;

  /* non terminals */
  static final int simple_variable = 26;
  static final int type_declaration = 29;
  static final int let_expression = 19;
  static final int struct_declaration_list = 43;
  static final int bitfield_list = 3;
  static final int declaration_list = 1;
  static final int pointer_list = 48;
  static final int initializer = 41;
  static final int field_list = 11;
  static final int enumerator = 38;
  static final int $START = 0;
  static final int record_expression = 22;
  static final int function_declaration = 16;
  static final int compound_statement = 25;
  static final int initializer_list = 42;
  static final int constant_expression = 39;
  static final int variable_expression = 32;
  static final int initialization = 9;
  static final int struct_or_union = 35;
  static final int for_statement = 15;
  static final int name = 5;
  static final int integer_literal = 18;
  static final int variable_declaration = 31;
  static final int if_statement = 17;
  static final int expression_array_type_list = 46;
  static final int operator_expression = 21;
  static final int bitfield_value = 34;
  static final int enumerator_list = 37;
  static final int parameter_type_list = 51;
  static final int expression = 8;
  static final int type_parameters = 13;
  static final int empty_array_type_list = 44;
  static final int record_type = 23;
  static final int brackets_list = 49;
  static final int type_name = 7;
  static final int expression_array_type = 47;
  static final int empty_array_type = 45;
  static final int parameter_list = 4;
  static final int assignment_expression = 40;
  static final int array_subscript = 28;
  static final int type_augments = 50;
  static final int variable = 30;
  static final int while_statement = 33;
  static final int field_var = 14;
  static final int string_literal = 27;
  static final int function_call = 52;
  static final int sequence_expression = 24;
  static final int parameters = 12;
  static final int expression_list = 10;
  static final int struct_or_union_declarator = 36;
  static final int declaration = 2;
  static final int nil_expression = 20;
  static final int type = 6;
}

