
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Mon Mar 10 00:02:10 CST 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SHORT = 17;
  static final int TIMES = 37;
  static final int GT = 43;
  static final int ARROW = 78;
  static final int DIVASSIGN = 57;
  static final int CONST = 9;
  static final int GE = 44;
  static final int PERIOD = 77;
  static final int REGISTER = 14;
  static final int ENUM = 24;
  static final int RBRACK = 74;
  static final int SIZEOF = 34;
  static final int COMMA = 68;
  static final int RBRACE = 76;
  static final int RPAREN = 72;
  static final int LBRACK = 73;
  static final int LT = 41;
  static final int INCREMENT = 66;
  static final int SUBASSIGN = 55;
  static final int DOUBLE = 21;
  static final int LBRACE = 75;
  static final int STRUCT = 22;
  static final int BWISEANDASSIGN = 59;
  static final int LPAREN = 71;
  static final int MODASSIGN = 58;
  static final int NOT = 47;
  static final int TILDE = 50;
  static final int LE = 42;
  static final int VAR = 6;
  static final int FLOAT = 20;
  static final int BITWISEAND = 53;
  static final int GOTO = 33;
  static final int EQ = 39;
  static final int LSHIFTASSIGN = 62;
  static final int MODULUS = 49;
  static final int LONG = 19;
  static final int PLUS = 35;
  static final int DIVIDE = 38;
  static final int WHILE = 27;
  static final int UNION = 23;
  static final int ASSIGN = 48;
  static final int CHAR = 16;
  static final int ADDASSIGN = 54;
  static final int DO = 29;
  static final int FOR = 28;
  static final int VOID = 15;
  static final int EXTERN = 11;
  static final int RETURN = 32;
  static final int ELSE = 26;
  static final int BREAK = 30;
  static final int FUN = 7;
  static final int INT = 18;
  static final int STRING_LITERAL = 3;
  static final int EOF = 0;
  static final int SEMICOLON = 70;
  static final int ELIPSES = 79;
  static final int MULASSIGN = 56;
  static final int DECREMENT = 67;
  static final int MINUS = 36;
  static final int OR = 46;
  static final int error = 1;
  static final int DECIMAL_LITERAL = 4;
  static final int CONTINUE = 31;
  static final int IF = 25;
  static final int BWISEOR = 51;
  static final int ID = 2;
  static final int COLON = 69;
  static final int BWISEXOR = 52;
  static final int BWISEORASSIGN = 60;
  static final int RSHIFTASSIGN = 63;
  static final int VOLATILE = 10;
  static final int CHAR_LITERAL = 5;
  static final int RSHIFT = 65;
  static final int BWISEXORASSIGN = 61;
  static final int NEQ = 40;
  static final int AND = 45;
  static final int STATIC = 12;
  static final int LSHIFT = 64;
  static final int TYPEDEF = 8;
  static final int AUTO = 13;

  /* non terminals */
  static final int declaration = 9;
  static final int enumerator_list = 16;
  static final int statement = 20;
  static final int Var = 2;
  static final int type = 3;
  static final int parameters = 5;
  static final int compound_statement = 18;
  static final int $START = 0;
  static final int initialization = 6;
  static final int type_parameters = 12;
  static final int statement_list = 19;
  static final int declaration_list = 11;
  static final int bitfield_value = 8;
  static final int Exp = 1;
  static final int parameter_list = 10;
  static final int struct_declaration_list = 14;
  static final int struct_or_union = 15;
  static final int constant_expression = 22;
  static final int enumerator = 17;
  static final int initializer = 7;
  static final int argument_list = 21;
  static final int bitfield_list = 13;
  static final int name = 4;
}

